version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/java
hooks:
AfterInstall:
    - location: removeapp.sh
      runas: ec2-user
 ApplicationStart:
    - location: runapp.sh
      runas: ec2-user
 
